name: iOS SDK Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest  # macOS runner

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'  # Make sure this matches your Xcode version

    - name: Run tests
      run: |
        xcodebuild test \
        -scheme iOS-native-embed-sdk \
        -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2"

